---
-  hosts: dpmawp
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"

     - name: Copy file to Backup location
       win_copy:
         src: C:\Websites\dpmawp.itsupport247.net\{{ webpost_file }} and C:\Websites\http.dpmawp.itsupport247.net\{{ webpost_file }}
         dest: C:\Websites\Backup\
         remote_src: True
         when: webpost_file.stat.exists == true
         
     - name: Delete file After Backup
       win_file:
         path: C:\Websites\dpmawp.itsupport247.net\{{ webpost_file }} and C:\Websites\http.dpmawp.itsupport247.net\{{ webpost_file }}
         state: absent
         when: webpost_file.stat.exists
         ignore_errors: yes
         
     - name: Copy webpost file
       win_copy:
         src: /var/lib/jenkins/workspace/Webpost/{{ webpost_file }}
         dest: "{{ item }}"
       with_items:
         - "{{ dpmawp.destination3 }}"
         - "{{ dpmawp.destination4 }}"

