---
-  hosts: dpmawp
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"
         
     - name: Check file {{ webpost_file }} exists
       win_stat:
         path: C:\Websites\dpmawp.itsupport247.net\{{ webpost_file }}
       register: stat_result

     - name: Copy file to Backup location
       win_copy:
         src: C:\Websites\dpmawp.itsupport247.net\{{ webpost_file }}
         dest: C:\Websites\Backup\
         remote_src: True
       when: stat_result.stat.exists


     - name: Delete file After Backup
       win_file:
         path: "{{ item }}"
         state: absent
       with_items:
         - "{{ dpmawp.destination3 }}"
         - "{{ dpmawp.destination4 }}"
       when: stat_result.stat.exists
         
     - name: Copy webpost file
       win_copy:
         src: /var/lib/jenkins/workspace/Webpost/{{ webpost_file }}
         dest: "{{ item }}"
       with_items:
         - "{{ dpmawp.destination3 }}"
         - "{{ dpmawp.destination4 }}"

