---
-  hosts: dpmawp
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"

     - name: Copy file to Backup location
       win_copy:
         src: "{{ dpmawp.destination3 }}{{ webpost_file }}"
         dest: C:\\Websites\\Backup\\

     - name: Copy webpost file
       win_copy:
         src: /var/lib/jenkins/workspace/Webpost/{{ webpost_file }}
         dest: "{{ item }}"
       with_items:
         - "{{ dpmawp.destination3 }}"
         - "{{ dpmawp.destination4 }}"

