---
-  hosts: dpmawp
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"

     - name: Copy file to Backup location
       copy:
         src: "{{ item }}" \ "{{ webpost_file }}"
         dest: C:\Websites\Backup\{{ webpost_file }}
       with_items:
         - "{{ dpmawp.destination3 }}"
         - "{{ dpmawp.destination4 }}"

     - name: Copy webpost file
       win_copy:
         src: /var/lib/jenkins/workspace/Webpost/{{ webpost_file }}
         dest: "{{ item }}"
       with_items:
         - "{{ dpmawp.destination3 }}"
         - "{{ dpmawp.destination4 }}"

