---
-  hosts: all
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"
   roles:
     - { role: webpost.yml, webpost_file_new: webpost_file, when: webpost_file == 'tfr_wpagthealthchkaction.asp' }
   
