---
-  hosts: all
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"
   roles:
     - { role: webpost.yml, when: webpost_file == 'tfr_wpagthealthchkaction.asp' }
       role_param: "{{ webpost_file }}"
   
