---
-  hosts: webpost
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"
   dependencies:
     - role: webpost.yml
       webpost_file: "{{ webpost_file }}"
   
