---
-  hosts: all
   tasks:
     - include_vars: vars.yml
       vars:
         webpost_file: "{{ webpost_file }}"
   roles:
     - { role: webpost, when: "{{ webpost_file }}" == 'tfr_wpagthealthchkaction.asp' }
   
